#!/bin/bash

PACKAGE_NAME="gitignore"
BUFFER_FILE="$1.gitignore"
HELP_TEXT=$(cat <<-END
This command will append the gitignore file of the specified language
from 'https://github.com/github/gitignore' to the end of your .gitignore.

Usage: gitignore [LANGUAGE_1] [LANGUAGE_2] [LANGUAGE_3] ...
END
)

remove_last_char() {
    echo $1 | sed 's/.$//'
}

show_guide()
{
    echo "Usage: $PACKAGE_NAME [LANGUAGE]"
    echo ""
    echo "Try '$PACKAGE_NAME --help' for help."
}

if [[ "$1" == "--help" ]]; then
  echo "$HELP_TEXT"
  exit 0
fi

# Check that there is only 1 argument
if [ "$1" == "" ]; then
    echo "$PACKAGE_NAME: Please specify the language to add gitignore!"
    show_guide
    exit 1
fi

IGNORE_URL="https://gitignore.io/api/"

# Get all language
for var in "$@"
do
    IGNORE_URL="$IGNORE_URL$var,"
done

IGNORE_URL=$(remove_last_char $IGNORE_URL)
wget -O .gitignore $IGNORE_URL
