#!/bin/bash

PACKAGE_NAME="gitignore"
GITIGNORE_API="https://gitignore.io/api/"
HELP_TEXT=$(cat <<-END
This command will append the gitignore file of the specified language
from 'https://github.com/github/gitignore' to the end of your .gitignore.

Usage: gitignore [LANGUAGE_1] [LANGUAGE_2] [LANGUAGE_3] ...
END
)

remove_last_char() {
    # shellcheck disable=SC2001
    echo "$1" | sed 's/.$//'
}

show_guide()
{
    echo "Usage: $PACKAGE_NAME [LANGUAGE]"
    echo ""
    echo "Try '$PACKAGE_NAME --help' for help."
}

# Help command
if [[ "$1" == "--help" ]]; then
  echo "$HELP_TEXT"
  exit 0
fi

# Check if folder is a git repository
if [ ! -d .git ]; then
  echo "You are not in a git repository. Please run 'git init' first.";
  exit 1
fi

# Check that there is at least 1 argument
if [ "$1" == "" ]; then
    echo "$PACKAGE_NAME: Please specify the language to add gitignore!"
    show_guide
    exit 1
fi

# Confirm overriding of .gitignore
if [ -e .gitignore ]; then
    while [[ "$confirm" != "y" && "$confirm" != "Y" ]]; do
        read -p -r ".gitignore already exist! Are you sure you want to override? [y/n] " confirm
        if [ "$confirm" == "n" ] || [ "$confirm" == "N" ]; then
            exit 1
        fi
    done
fi

IGNORE_URL=$GITIGNORE_API
errors=""

# Get gitignore.io API url
for var in "$@"
do
    header_code=$(curl -o /dev/null --silent --head --write-out '%{http_code}\n' "$GITIGNORE_API$var")
    if [ "$header_code" != 200 ]; then
        errors="$errors$var "
    fi
    IGNORE_URL="$IGNORE_URL$var,"
done

# Check if there are any errors
if [ "$errors" != "" ]; then
    echo "$errors"
    echo "The following languages are not found: $errors"
    exit 1
fi

IGNORE_URL=$(remove_last_char "$IGNORE_URL")
wget -O .gitignore "$IGNORE_URL"
